### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by FristyFlakes** [legendoftelegram/captionbot#2]
Is it possible for the bot not to clear captions added before posting to channel but adding caption underneath them.. It automatically clears old caption and replaces it with just the new one

**Comment by legendoftelegram** [comment]
hey install from old-+-custom-caption(doc) this branch it will work

**Comment by FristyFlakes** [comment]
![Screenshot_20201109_131822](https://user-images.githubusercontent.com/71187213/98540340-1486a180-228e-11eb-9632-6456d8a03ad5.jpg)

Screenshot Above

**Comment by FristyFlakes** [comment]
Error when using the branch
